[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.venvShellHook"
]

[phases.install]
cmds = [
  "npm install",
  "python -m venv /app/venv",
  ". /app/venv/bin/activate && pip install --upgrade pip",
  ". /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && npm start"
