[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311.withPackages (ps: with ps; [ pip ])"
]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[start]
cmd = "npm start"
